---
services:
  terraform:
    image: hashicorp/terraform:latest
    env_file: .env
    working_dir: /opt/app/
    volumes:
      - ~/.aws:/.aws
      - .:/opt/app:rw
      - ./passwd:/etc/passwd:rw
      - ~/.terraform.d/plugins:/opt/app/.terraform.d/plugins
      - ~/.ssh:/opt/app/.ssh:rw