name: OIDC test

on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::905418016289:role/cfst-1449-314040f74818fc5af46c82a91bc9f0-LambdaRole-39s5vE2uQAnZ
          output-credentials: true

      - name: AWS Creds
        run: |
          ./scripts/aws_credentials.sh 
        env: 
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
          
      - name: 3m s3 test
        run: make test
