name: AWS OIDC Auth with AWS CLI

on: # yamllint disable-line rule:truthy
  push:

permissions:
  id-token: write # Required to fetch the OIDC ID token
  contents: read  # Required to checkout the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Get OIDC token and assume role
        id: assume-role
        run: |
          # Fetch the OIDC ID token
          # This token is a JWT that GitHub provides and is signed by GitHub's OIDC provider.
          OIDC_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$secrets.ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")

          # Assume the IAM role using the OIDC token
          # Replace 'arn:aws:iam::381492001354:role/gha_role' with your actual IAM Role ARN
          ASSUMED_ROLE_CREDENTIALS=$(aws sts assume-role-with-web-identity \
            --role-arn "arn:aws:iam::381492001354:role/gha_role" \
            --role-session-name "GitHubActionsSession" \
            --web-identity-token "${OIDC_TOKEN}" \
            --duration-seconds 3600 \
            --output json)

          # Extract credentials and set them as environment variables for subsequent steps
          echo "AWS_ACCESS_KEY_ID=$(echo $ASSUMED_ROLE_CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $ASSUMED_ROLE_CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $ASSUMED_ROLE_CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

          # Set the AWS region for the CLI
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV # Replace with your desired AWS region

      - name: Verify AWS CLI access
        run: |
          aws sts get-caller-identity
          aws s3 ls # Example AWS CLI command