name: Parent Workflow

on:
  push:
  workflow_dispatch:

env:
  MODULE_NAME: "My Module"

jobs:
  echo-init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize echo
        run: echo time to run"

  call-child:
    needs: echo-init
    uses: ./.github/workflows/child.yml
    with:
      input_value: ${{ env.MODULE_NAME }}

  echo-result:
    runs-on: ubuntu-latest
    needs: call-child
    steps:
      - name: Echo value returned from child
        run: |
            echo "Child returned: ${{ needs.call-child.outputs.child_output }}"